create table public.comments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  project text not null,
  location text null,
  author text null,
  comment text null,
  constraint comments_pkey primary key (id)
) TABLESPACE pg_default;